export { default as Tab } from "./Tab"
export { default as Tabs } from "./Tabs"
export { default as TabList } from "./TabList"
export { default as TabPanel } from "./TabPanel"
export { default as TabPanels } from "./TabPanels"
export { default as SimpleTab } from "./SimpleTab"
export { default as SimpleTabs } from "./SimpleTabs"
